### ISSUE TITLE
Can't get the current classroom automatically checked when starting Veyon master on windows10

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#110]
Hello again

When i check "automatically switch to current room at start" in Veyon configurator and when i run veyon master the current room isn't automatically displayed in the room/computer screen.
It is necessary to click the computer rooms tab to display the classroom and then to check the classroom box to get the monitors screen. The classroom box isn't checked by default and it is necessary to check the box each time when starting the master.
Why the current room isn't automatically displayed whith box checked?
I send you a screen capture showing the problem
![veyon capture](https://user-images.githubusercontent.com/29846901/30478360-098d9fda-9a11-11e7-8997-f2638cd97aa7.JPG)

**Comment by orion777** [comment]
Here is another capture screen also showing the computer box unchecked
![veyon capture](https://user-images.githubusercontent.com/29846901/30478506-9d585fb6-9a11-11e7-949b-d9a6eac161bd.JPG)

**Comment by tobydox** [comment]
For this feature to work you have to add the master/teacher computer to the room as well because otherwise Veyon doesn't know which room the master/teacher computer belongs to. You can then enable the option "hide local computer" so it doesn't appear in the Veyon Master program and doesn't disturb you.

**Comment by orion777** [comment]
Thanks you, i have the current classroom displayed now.
