### ISSUE TITLE
Integration with active directory

### ISSUE THREAD

**Issue by ampcnet** [veyon/veyon#144]
Hi,

I am new to Veyon,we have installed and configured the software,but some how having issues with connecting the devices,Every time we click on remote control it comes up with Ip address,
We have 3 computer lab and we have DHCP which keeps changing.

Is there any option to have all the computers in the room to be monitored without specifying IP address/hostname

**Comment by farmeunit** [comment]
Right-click on a machine instead of using buttons at the top.  I noticed that the other day.  The buttons at the top are for multiple machines.  For example, if you use the Lock at top, it will lock all machine.  Remote will ask for name, because you can't control all at once.  I know LANSchool has ability to control all at once, which would be nice, but not sure how they do it.

**Comment by tobydox** [comment]
In your case you have 2 options: using the builtin LDAP Basic plugin or using the Network Discovery add-on. Both can handle dynamic environments quite well depending on the actual scenario.
