### ISSUE TITLE
Veyon Configurator Won't Start

### ISSUE THREAD

**Issue by Roidz25** [veyon/veyon#168]
I'm running Veyon 4.0.2 Win64 on Windows 10
Program installs fine but will not load the configurator (Window does not open but process is displayed in task manager). The master loads fine but obviously I cant add computers or change settings. I tried changing the "EnableHighDPIScaling": true, but it did not resolve the issue. 
Is there a way to add the computer Hostnames without the configurator?

**Comment by Roidz25** [comment]
I Have since installed veyon on my laptop (also win 10) and the configurator loads. If I add the computers in the lab using this laptop can I transfer the .json config file to the other master computer?

**Comment by Roidz25** [comment]
Oh well I'm answering my own questions. The Veyon Configurator did actually pop up on the original computer (After half an hour!) I checked the logs and these are the only 2 entries for veyon configurator:
2017-11-01T15:37:14.533: [INFO] App.Exec
2017-11-06T10:55:44.225: [INFO] App.Exec
Which are the 2 occasions the program successfully loaded. No entries for other attempts.
I managed to get the computers added today!

**Comment by wdrcomputers** [comment]
I'm having the same problem version 4.0.2. Win 10 64bit.  After the installation of veyon service only (What I call a student install) you launch configurator and nothing happens.  If you look at task manager you can see the program running. It just consumes more and more memory, going up by about 20k per second.  Like a memory leak in the code. Once it gets up to around 20,000k in size ( a few minutes later) the memory size jumps up and down a few 1000kb around that 20,000k mark until eventually the configurator loads on the screen (Haven't timed it, but feels like about 30 minutes later).  When the program does displays on the screen the memory usage is 106,040 kb. Hope this help in the troubleshooting the bugs in the code.
Cheers
Warren

**Comment by tobydox** [comment]
Is your computer part of a domain? If so, how many user groups does your domain have? Is your domain controller reachable?

**Comment by wdrcomputers** [comment]
Sorry Tobias for not getting back to you earlier.  Yes it is part of a
domain and a very,very large one at that. I don't know the exact numbers
but I have been told it is the largest in Austrailia.  It is the public
school network for NSW which is the biggest state in Australia (population
wise).  RODC controller is onsite, so yes it is reachable. There would be
tens of thousands of group across the whole domain.

Since the last time we talked I've made some progress. If I don't run the
configurator at the end of the setup process by removing the tick box. Then
do a registry merge with all my client setting.  The configurator will
start without delay after this step.
Also in regard to the Lock screen.  I was going to come back to the
computers later to uninstall/re-install the interception software but found
that the lock screen worked OK later on.  I don't know if this can be put
down to a reboot or something else.

Cheers
Warren

**Comment by tobydox** [comment]
Yeah this issue only occurs if the "local data/user/groups" backend is used. It then queries all groups from DC in order to populate the access control configuration page. I just pushed some commits to query domain groups only optionally by adding a checkbox in the access control configuration page. This change will be part of Veyon 4.0.4.
