### ISSUE TITLE
Screen sharing doesn't work

### ISSUE THREAD

**Issue by Federica81** [veyon/veyon#185]
I'm not able to share the screen of my computer to that of my students. I've read that this answer was fixed but I don't understand how. I read that I must disable encodings based on zlib streams. But how? Where? What is the zlib streams?
Thank you,
Federica

**Comment by jaucay** [comment]
@Federica81 Hello there. As far as I know, this fix has been integrated into version 4.0.2, so with a simple upgrade to the current release will apply the fix for you. Now, you may still experience issues with full-screen and windowed mode like I did. In that case, make sure that both machines are able to communicate with each other (via ping) and that the demo server ports are open and accepting connections on the master and client machines. If that still does not fix the issue, try placing both machines on the same subnet and try again. If that fixes your issue, then its probably packets being dropped when traveling between networks. In that case, check or ask someone to check if TCP <demo server port (default 11400)> traffic is being allowed between networks. This final step got me up and running again.

**Comment by tobydox** [comment]
@Federica81 : You do not have to disable anything, the zlib streams are an internal technology which isn't used since 4.0.2 for demo mode. You don't have to worry about it. If you're running 4.0.2 please follow the steps provided by @jaucay
