### ISSUE TITLE
Disable remote Keyboard and mouse on remote control

### ISSUE THREAD

**Issue by strc12** [veyon/veyon#241]
Is there a way of disabling remote mouse and keyboard when remote controlling - I remember that feature in iTALC but can't see any way of activating it in Veyon.

Annoying students keep moving the mouse when I am remote controlling!

**Comment by tobydox** [comment]
Thank you for your suggestion and sorry for the late reply! I see the demand but there's currently no reliable way to achieve that on all platforms which is why we did not implement it in Veyon yet. However I added your suggestion to https://github.com/veyon/veyon/wiki/Brainstorming so it might be implemented by volunteer developers in the future.
