### ISSUE TITLE
When I git clone veyon master, cmake gives me 4.0.4

### ISSUE THREAD

**Issue by jradxl** [veyon/veyon#283]
Hi,
You have release 4.0.5 available, but when I clone master and start build, I get following at end of cmake
* Version                     : 4.0.4.373 (4.0.4-373-gd3cb4935)
Please advise

**Comment by tobydox** [comment]
Thanks for reporting! For Veyon 4.0.x you have to use the branch "4.0" (which is recommended for production). The master branch is almost 400 commits ahead of the last stable release tag (please update again to also receive the final 4.0.5 tag) that's why you get the version number you can see here. This will change as soon as we released the first alpha version for Veyon 4.1.
