### ISSUE TITLE
Veyon for Linux is missing systemd-logind fallbacks for logoff/shutdown/reboot

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#312]
Please improve logoff/shutdown/reboot mechanisms for Linux, including some other popular DEs (MATE, LXDE, Cinnamon, etc.) as well as a systemd-logind fallback (Veyon currently only includes a ConsoleKit fallback).

You can take this example from Epoptes: https://github.com/Epoptes/epoptes/blob/master/epoptes-client/endsession

**Comment by stephaniebamerico** [comment]
I was going to create a issue about it. Currently I can not turn off the Gnome computers using Veyon, because the `dbus-send --session --dest=org.gnome.SessionManager --type=method_call /org/gnome/SessionManager org.gnome.SessionManager.RequestShutdown` method displays the error: 
> "Error org.freedesktop.DBus.Error.UnknownMethod: Method RequestShutdown is not implemented on interface org.gnome.SessionManager".

Other users have [reported](https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1557523) that this method no longer works on Ubuntu 16.04.

Veyon already tries to shut down using ConsoleKit, but this solution is inconvenient in our case. We have not installed by default on machines, and even after installed, I needed to add the` --print-reply` parameter to work (it does not come by default in Veyon).

A good alternative to shutting down machines is using [logind](https://askubuntu.com/questions/630279/shutdown-command-for-gnome), as it is standard on virtually all systems. The command `dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true` shuts down the machines without problems! It's a small change, but that would solve a big problem.

P.S.: A more extensive discussion of the problem can be found [here](https://gitlab.c3sl.ufpr.br/le6/SCRUM/issues/482#note_35107), but it is in Portuguese.

Thank you!

**Comment by tobydox** [comment]
Thanks for the input! A complete rewrite of the DBus calls is being worked on ;-)
