### ISSUE TITLE
Create a flatpak version of Veyon on flathub

### ISSUE THREAD

**Issue by LeandroStanger** [veyon/veyon#329]

**Comment by tobydox** [comment]
Thank you for your interesting suggestion! We'd love to support new package formats but when elaborating the flatpak technology I found out that Veyon likely wouldn't work with flatpaks. The problem is that it ships a systemd service (and is based on this service) which is not supported by flatpak at all. Only having Veyon Master as a flatpak wouldn't help that much as you still would have to install the service regularly. Feel free to provide us with some help or your experiences with flatpak.
