### ISSUE TITLE
Windows: CMD/Ping

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#335]
When previewing computers, PING and CONHOST are started regularly for all previewed computers. Can Veyon ping computers without the need of external commands in the future?

**Comment by tobydox** [comment]
This is actually only launched for computers which the Master can't connect to. Using ping it determines whether the computer is running/reachable at all. pinging without external tools is difficult as on some platforms you must not send ICMP packages as non-privileged users. That's why for example on Linux the suid-bit is set for ping. Feel free to propose a different solution ;-)

**Comment by ldlx** [comment]
Veyon already uses some TCP-based connections, you could try to open a TCP-connection on one of the ports used by Veyon (with a short timeout, Ping has a 3 seconds timeout AFAIK). If the TCP connection is successful, the client is reachable. If not, not.

**Comment by tobydox** [comment]
Veyon uses ping only if the TCP connection fails in order to determine whether just the service is not running or the computer is not reachable at all (red monitor icon vs. grey monitor icon).

**Comment by tobydox** [comment]
Do you have a suggestion to improve the current implementation?

**Comment by ldlx** [comment]
Although this is related to Python (and might not be cross-platform), maybe it helps:
https://scapy.net/
https://stackoverflow.com/questions/1189389/python-non-privileged-icmp

**Comment by dxdemetriou** [comment]
An efficient implementation could be this:
https://www.codeproject.com/Articles/18908/Simple-Ping-Utility-with-GUI
I don't know if it's possible to be implemented and used only when .NET is available (as it's cross platform now).
An least, on Windows, the ping.exe is a headacne by itself, and this method had saved me a lot of times.
