### ISSUE TITLE
Use German translation also for Swiss German

### ISSUE THREAD

**Issue by THS-on** [veyon/veyon#361]
Currently there is no translation for Swiss German and veyon starts in English, which isn't optimal.
Is there a reason not to use the current German translation for all german speaking countries?

**Comment by tobydox** [comment]
Thanks for the feedback! This is indeed not optimal but probably a bit difficult to solve, because the name of the translation files usually include both country and language code (i.e. there's a translation for de_DE but not de_CH). I'll be working on a solution. In the meanwhile you can configure the user interface language explicitely using Veyon Configurator.
