### ISSUE TITLE
Master does not automatically display the clients' screen.

### ISSUE THREAD

**Issue by userveyon** [veyon/veyon#369]
Hi. First, thank you for the Veyon software.

I have installed Veyon in 16 machines with Windows 7 (1 being master) and when I open the Master Veyon does not show the screens (only red/gray monitor), but if I remove the network plug (RJ45) on one of the client computers and put it back, then the screen appears in the master and all work correctly.

Anyone have any idea how I could fix this, for the master computer automatically show the screens without having to do this on each client machine?

Another question, for anyone using dhcp (like me) is there any form of setting indicated (in master computer or something specific)?

I am using the key method and I configured the room adding the 15 computers in the master, but only with fields name, hostname and mac address, ip no.

Thank you.
PS: Sorry for the bad translated english.

**Comment by ldlx** [comment]
I assume all computers are in the same subnet and no Routing or VLANs in place. Are you using IP or Hostname to connect to the clients? Is name resolution working correctly and do the clients register successfully at the DNS server? Have you tried assigning a static IP address to clients or putting an entry for the client in the hosts file (just for testing purposes)?

**Comment by flaviusioan69** [comment]
Same problem here.

And i found many others:

Dont know why, but also im geting the message : input the ip or hostname of the selected computer.

I think this veyon is more bugsy then former Italc 😯

**Comment by tobydox** [comment]
@flaviusioan69 What you see is an intended feature ;-) If you chose "remote control" from the toolbar and have no or more than one computer selected, Veyon will explicitely ask which computer to remote control. This is also a shortcut to remote non-visible control computers instantly so you do not have to check them in the computer manager first. Veyon actually is supposed to have less bugs than iTALC and we're really working on improving it. If you find bugs, don't hesitate to report them and/or give additional information in existing reports.

Regarding the original bug report: this is really a strange behaviour we have to track down. It looks like it can't open an initial connection to the clients. Are the clients powered on already when starting Veyon Master? Or do you start clients later? As already asked by @ldlx: does using IP addresses (rather than hostnames) change the behaviour?

**Comment by userveyon** [comment]
Apparently solved! Initially I was only using the hostname to list the computers in room (master configuration), now I have put the ip of each one and the client screen appears automatically in Veyon Master.

**Comment by tobydox** [comment]
Thanks for reporting back! I recently improved the code for initiating network connections so things will be improved in the final 4.1 release next week.
