### ISSUE TITLE
Clients connect and disconnect constantly after the last update

### ISSUE THREAD

**Issue by claudiobjunior** [veyon/veyon#391]
Good afternoon!! I have two computers that run Veyon Master through Ubuntu and twenty Windows 10 stations that run the Veyon client. After upgrading to the latest version, the stations apparently connect and then disconnect from the Veyon Master constantly, which makes it impossible to use. The screens of the stations blink all the time! This problem gets worse in the stations where I also updated to the latest version of Veyon. Anyone else noticed this happening? What can I do to resolve this?

**Comment by gorru** [comment]
I have the same problem:
both client and server are running on Ubuntu 16.04.
I noticed that veyon-ctl service status command return logs related to pam_unix and pam_systemd
```
session opened for user user_name
cannot create session: already occupied by a session
```

**Comment by ysalmon** [comment]
I seem to be affected by the same problem after upgrading to 4.1.1 on my Linux stations today : I did not check the logs (had to go away) but :

- screens remain gray in the preview
- username (lightdm as the station are displaying the login prompt) is like blinking at an irregular interval for each machine (the information seems to be lost a fraction of second after it was acquired)
- using "Remote display" on a machine gives a window with "Connecting........" for quite a long time and a black screen with some strange white symbol in the middle (which is not what is displayed on the remote machine).

**The github master version I used for earlier tests related to #365 did not exhibit this behaviour.** Which means the culprit is more recent than c859cf5191c9d4d81e7a75a517c84c883b8c76d9

 (disclaimer : I also did a general ```apt-get upgrade``` on these Debian 9 so the software environment evolved)

**Comment by tobydox** [comment]
Thanks for the feedback and investigations! What update interval do you have configured? Are you running 32 or 64 bit version?

**Comment by ysalmon** [comment]
64bits. I did not change the configuration when updating ; I had a Json config file on my master computer (generated in July) that I pushed to the others after upgrading veyon. It contains the following (I grepped for interval)
```
        "FramebufferUpdateInterval": "100",
        "KeyFrameInterval": "10",
        "ComputerMonitoringUpdateInterval": 1000,
        "UpdateInterval": "120"
```

**Comment by ysalmon** [comment]
Test results :

- old deb generated in July (so problem does not come from system upgrade) WORKS wrt this issue
- version of July 16 (5c1271a5aeec0cd7649138ba3e02b5c57073d1b2) Preview ultimately seems to work wrt this issue but some "flickering" of username in the beginning and single remote view does not work (connecting.......) so DOES NOT WORK
- version of July 13 (110ad3bd9a6b84a27fa57e91c3aa8e29a46977cc) DOES NOT WORK

Which is strange because the deb generated un July probably is one of them ; it is definitely more recent than July 13.

So I suspect that the problem comes from one of the submodules : for the different versions I did a simple checkout without recursing for submodules to avoid recompiling them on the high school's computer which is so slooooooooow. I might try to compile different version at home with appropriate versions of the submodules but it is logistically complicated as I cannot upgrade the high school's computers from home.

**Comment by ysalmon** [comment]
So, after bisecting versions, it seems that the bug was introduced by commit 788e70bfc77d968222cbe32f96e8267a1959c56f, which is an update of submodule libvncserver. This confirms my earlier suspicions about submodules. Indeed, I just compiled and installed v4.1.1 with the libvncserver that existed before 788e70bfc77d968222cbe32f96e8267a1959c56f, and this works.

**Comment by tobydox** [comment]
Ok so there seems to be a problem with slow or laggy clients then. Can you roll back to the latest version and try to increase the number of retries from 100 to e.g. 1000 in 3rdparty/libvncserver/libvncclient/sockets.c (search for "retries")?

**Comment by ysalmon** [comment]
v4.1.1 works with your suggested modification.

**Comment by hehu01** [comment]
Hi, I am new to Veyon. Need some advice on installation. I want to try a Ubuntu 20.04 LTS master/server and 2 unit WIndows clients. Are there few things I need to modify or can I just do like the normal as if I had Windows master?clients?
Thank you very much in advance for your good advice.
