### ISSUE TITLE
REQUEST: Option hold with mouse.

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#394]
Add an option (combobox), to select an action to hold with the mouse on the client.

![screenshot_6](https://user-images.githubusercontent.com/679128/44283991-6d456c00-a236-11e8-888e-c3ba0521be66.png)

**Comment by pauloboc** [comment]
Is this still in the plans?

**Comment by SlrG** [comment]
I really would like to have this, too. It was a really helpful feature of iTalc. Maybe let the user hold Ctrl when pressing the left mouse button to arrange the thumbnails instead of just dragging them? Or leave the dragging as is and make the user hold Ctrl if he wants to click to open the remove view? Releasing the left mouse button should close the remove view, as it was on iTalc.

Also please make the window appear on the same screen the veyon master is running on or make it configurable. The size of the window should be defined by the size of the screen and the content scaled accordingly.

To describe our setup:
We have a main monitor mirrored to a projector which is used to display a presentation or what the teacher is showing for the students. On a second screen, we have Veyon master running, so the teacher can always see, what the students are doing. If the teacher wants to see enlarged, what a certain student is doing, he has to choose remote view for this student. The remote view window then always goes to the main screen, disturbing the view for the other students, until the teacher moves the window to the second monitor and out of view. When opening a new window for another student, this process has to be repeated each time, as the window position is not remembered and always on the main display. 

On iTalc when holding the left mouse, a large (but scaled to the screen size) preview window was opened on the same screen, the master was running on, never disturbing the view on the main screen. It closed automatically, when the teacher released the mouse button. This was much easier and more useful for our teachers, I have had many complains regarding this issues, since we switched to Veyon.

Thank you very much for this great software! I could not imagine teaching without it ever again.

**Comment by pauloboc** [comment]
@tobydox 

Are there plans to implement?

**Comment by tobydox** [comment]
We now have the new Spotlight panel which provides a similar functionality. The originally requested feature will therefore not be implemented, also since it's technically difficult to change the icon size of items individually in a QListView (which was not used in iTALC). I hope you find the new Spotlight panel useful and it's a proper replacement.
