### ISSUE TITLE
Error installation 4.1.3

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#427]
**Veyon 4.1.3  // Windows 10 64bits**

![screenshot_2](https://user-images.githubusercontent.com/679128/46363969-df3d0d80-c64a-11e8-8c77-d2266ecc1db5.jpg)

**Run "install.bat" with admin privileges.**

![screenshot_1](https://user-images.githubusercontent.com/679128/46363973-e106d100-c64a-11e8-9a46-211cc455dfd8.jpg)

**Comment by tobydox** [comment]
Can you try to uninstall Veyon first and then try to re-install?

**Comment by pauloboc** [comment]
I uninstalled, **rebooted** the computer, then the installation was successful

**Comment by o71** [comment]
Hello,

I have the same problem. Until now I used a GPO successfully with the following script to update all my computers :
`\\X.X.X.X\scripts\veyon\veyon-4.1.3.0-win64-setup.exe /applyConfig=\\X.X.X.X\scripts\veyon-client.json /S /NoMaster /D=%ProgramFiles%\veyon`

But because of this problem, which requires uninstallation and reboot, I can't do it.

So for the moment, I stayed in version 4.1.2.
Is a fix in preparation? Do I have to wait for the next version?

Thank you for your excellent job.
