### ISSUE TITLE
Problems with remote control and login

### ISSUE THREAD

**Issue by esmuigors** [veyon/veyon#428]
Dear developers and users,

Recently we have **veyon** v. 4.1.2 installed in the computer class, all machines _ubuntu 18_, logon authentication (key identification did not work). Machines can be seen in the monitoring screen. However, when trying to remote-control them, strokes on Shift key, seem to have no effect on the client PC, as can be seen from typing remotely. Since my password contains special characters, I cannot log in after the client computer has gone to sleep. CapsLock does work, but this does not help for special characters...

Another possibly connected issue is that if I request the login screen, it appears on client PC' s display, but the screen in veyon remote connection does not update and I am stuck.

Please tell me what information I shohuld provide for You if You think it may be solvable. The only lines after login which contain 'veyon' are available via the link below, together with surrounding lines from networking and gdm3.
[https://pastebin.com/pBi9zFzV](https://pastebin.com/pBi9zFzV)

**Comment by tltucker** [comment]
The problem is with the vnc server, but here is a fix.
Load veyon-configurator
go to service
under the VNC server choose Builtin VNC server (x11vnc)
under custom extensions add -nomodtweak

![image](https://user-images.githubusercontent.com/34378870/49045092-7af38180-f195-11e8-98b0-cafc8e2faba9.png)

This has to be done on both master and remote
