### ISSUE TITLE
Domain Security Groups

### ISSUE THREAD

**Issue by SICTech** [veyon/veyon#471]
When the "Enable usage of domain groups" is enabled within access control, Veyon scans the entire WAN i.e other schools for the groups. Would it be possible to enable Veyon to just pickup domain groups within the local LAN\DC. Maybe a way of limiting the scan within an ip range or pointing veyon at the local DC.

**Comment by tobydox** [comment]
Thank you for your bug report! Veyon simply uses the primary domain controller for retrieving domain groups. If you have a WAN-wide DC I fear there's nothing we can do here. You could try to use the LDAP/AD backend (instead of the default system user groups backend) even though it requires some setup efforts. Once running you can filter groups easily by configuring the appropriate LDAP filter. That's all I can advice here for now.
