### ISSUE TITLE
Logon multiple computers at once.

### ISSUE THREAD

**Issue by Lrobben52** [veyon/veyon#506]
Hi Toby,
Would it be possible to add a LOG ON ADMIN button next to the log off button on top of the screen.
Sometimes administrators have to interfere quickly in a classroom and when you have to logon 20 computers, ... it's slowing down the work.
In the master we could set the admin credentials (hidden) for logon at once.
I'm testing 4.20RC, so far so good, Thanks.

**Comment by TBastien** [comment]
Hello, we are in the same case with a demand from primary schools that use generic accounts. The ability to open the same Windows session of all the posts since the Master would be a big advantage. Have you planned this feature? Can we help, time or funding to speed up the addition of this feature?
Thanks

**Comment by tobydox** [comment]
Good news: mass logon will be implemented in Veyon 4.3 which will be release in Q4/2019. A release candidate might be released even earlier.
