### ISSUE TITLE
Wake On LAN with multiple NICs

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#53]
Does Veyon support sending WOL packets to all NICs of the master computer?

Background: Most WOL tools only send the WOL packet to the first NIC. When the network is split up into several subnets, you can only send packets to computers in the subnet when you have an interface in that subnet. So an admin computer/VM would have a network interface for each network, but the WOL software needs to send the WOL packet to all interfaces at once.

**Comment by tobydox** [comment]
It doesn't send on a dedicated NIC but 255.255.255.255 so I guess it's up to the OS to decide which NIC is used.

**Comment by ldlx** [comment]
If you like I can give you my PowerShell script which supports multi-NIC WoL to adapt it to Veyon. Using PowerShell itself could fail, as the execution policy could be restricted on the computer running Veyon Master.

**Comment by tobydox** [comment]
Thank you very much for your offer! However in order to keep Veyon fully cross-platform compatible I'd only integrate solutions implemented in C++/Qt. Feel free to extend the PowerControl plugin, specifically the function "broadcastWOLPacket". Alternatively you could extend the PlatformNetworkFunctions implementation and add a function which sends a UDP broadcast on all NICs. This function would have to be implemented in platform support plugins.
