### ISSUE TITLE
Log In User button not opening window in Veyon Master.

### ISSUE THREAD

**Issue by jcarpenterMMS** [veyon/veyon#589]
Log In User button not opening window in Veyon Master. Nothing at all happens.

I have tried version 4.2.x and 4.3.1. Both do not have a working log in users button on my system.

Any ideas what could cause this?

**Comment by tobydox** [comment]
Thank you for your bug report! This specific issue happens if confirmation of unsafe actions (such as the related user log off feature) is enabled. It will be fixed in 4.3.2. Until this version is available you can disable the unsafe feature execution confirmation in the configuration as a workaround.
