### ISSUE TITLE
Permit to disable entering a hostname or IP address for remote vue and control

### ISSUE THREAD

**Issue by baby-gnu** [veyon/veyon#652]
Hello.

On Veyon `4.4.1` on Windows 10, in the master view, it's possible to enter a hostname or an IP address for remote control and this bypass any association between the master and the remotes computers.

With `4.3.0`, we disabled both features and used a possible bug that when viewing the remote desktop, we had the button to enable the remote control.

We are a little bit concerned by this since a master can view any computer as soon as the user know it's IP address or hostname (and it has the rights which is true for teachers).

Is it possible to disable the manual input of hostname or IP address and limit possibilities to displayed computers?

![remote-control-ip](https://user-images.githubusercontent.com/1233212/88190432-cb043f00-cc29-11ea-8ee1-092182b6ca18.png)

**Comment by PappBence** [comment]
+1

**Comment by tobydox** [comment]
We strongly suggest to configure access control rules such that teachers are only able to access the machines they actually are supposed to (for example Veyon offers rules/conditions to limit the access to the same room so teachers can't access computers rooms other than the one their own computer is located in). Just disabling/hiding the dialog would not bring real security gains since teachers still could use ``veyon-cli remoteaccess control <IP>``.

Anyway we improved the remote access feature a bit in 4.7.1 such that it only prompts for a hostname/IP if no computer is selected. Otherwise it opens remote access windows for all selected computers.

Given the two facts I consider this issue as resolved from a developers perspective. Feel free to append additional suggestions or post questions to our community forum at https://veyon.nodebb.com
