### ISSUE TITLE
Authentication keys issue

### ISSUE THREAD

**Issue by Dillton** [veyon/veyon#653]
Hi, I have installed Veyon version 4.4.1.0 and I have problem with authentication keys, Everything working fine when I use only one pair of keys but when I create more than one pair I am unable to connect to any of my PCs. Simply I have more PC groups and I want use more key pairs to access them, to have he access separated if you understand what I mean, I dont want to have one pair of keys for all PCs because I need to give access to specified users to specified PC group. Anyone have the same issue? Can anyone help me please? Thanks

**Comment by TheNothingMan** [comment]
Is there anything new on this? I discovered a similar, if not the same, problem in 4.7.1-3. Setting up multiple PCs with one keypair worked fine, then I wanted a separate key for a different set of computers.
I'm pretty sure that it worked for a while (2-3 days) with both keypairs installed on my master computer. However, came back after a week of vacation and couldn't authenticate. Deleting the second pair of keys from master seemed to solve the issue, but this is not the optimum.
Any help would be appreciated.

**Comment by Dillton** [comment]
Hi, not from my side. This issue still persists. Last tried few weeks ago. So far I solved this by connectin Veyon to our domain in Active Directory however this "hotfix" is not usable on all our computers we need to manage.

**Comment by tobydox** [comment]
I think there are two possibilities:

1) Explicitly specify the authentication key to use when starting Veyon Master using the `VEYON_AUTH_KEY_NAME` environment variable (requires Veyon 4.7.2 or newer since it has been broken in previous releases). If not specified explicitly, there's currently no defined behavior for the key file selection master-side.

or

2) Create another "master"/"super" key for the computer which is going to monitor all the different computer groups (and remove all other private keys from that computer). Then deploy the public master key to *all* computers. Veyon Service can handle multiple keys easily and no key has to be specified explicitly since Veyon Master informs the client which key to use for authentication.

I hope this helps.
