### ISSUE TITLE
Feature: computers discovery

### ISSUE THREAD

**Issue by JintangMai** [veyon/veyon#656]
Hi all,

The latest version of Veyon add clients manually at Veyon Configurator.
I have an idea of a feature: computers discovery.
Basic idea: once the client start the service, it will broadcast a UDP packet to full subnet. The UDP packet contain client IP, host name and other information.
Etc, master's IP is 192.168.0.100, client's IP is 192.168.0.10, mask is 255.255.255.0, gateway is 192.168.0.254.
Once the client start the veyon service, it will broadcast a UDP packet to 192.168.0.255.
Every one at the same subnet will receive the packet, but only the master will handle it.
Master receive the UDP packet and handle it, know the client IP, host name and other information. Master add the client to computer list and show to user.

If have similar feature, please tell me how to use it. 
If not, I can begin this new feature. 
Thank you!

**Comment by tobydox** [comment]
Thank you for your suggestion! Actually that's what the NetworkDiscovery add-on already does, even though it makes Veyon Master scan for hosts running the Veyon Service instead of receiving broadcasts (which would not work across network boundaries). You can try the NetworkDiscovery add-on by installing the add-ons package. It can be configured through the Veyon Configurator. The demo version will work for a few minutes in Veyon Master.

**Comment by JintangMai** [comment]
> Thank you for your suggestion! Actually that's what the NetworkDiscovery add-on already does, even though it makes Veyon Master scan for hosts running the Veyon Service instead of receiving broadcasts (which would not work across network boundaries). You can try the NetworkDiscovery add-on by installing the add-ons package. It can be configured through the Veyon Configurator. The demo version will work for a few minutes in Veyon Master.

Thankyou! : )
