### ISSUE TITLE
Running Veyon 4.4.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by geekthought** [veyon/veyon#662]
When i try to start veyon-configurator via terminal I get: 

"PlatformPluginManager: no platform plugin available!"

I found [this](https://veyon.nodebb.com/topic/109/platformpluginmanager-no-platform-plugin-available-since-4-0-9-and-even-with-4-1-1) thread and tried 4.0.8. with which i can start the configurator. 

What went wrong?

**Comment by tobydox** [comment]
Are you using the official packages for Ubuntu or the Veyon PPA? Are all package dependencies ok? Or did you compile Veyon on your own?

**Comment by geekthought** [comment]
> Are you using the official packages for Ubuntu or the Veyon PPA? Are all package dependencies ok? Or did you compile Veyon on your own?

The Deb from the download page for ubuntu 20.04: https://veyon.io/download/

**Comment by tobydox** [comment]
Thanks again for reporting this problem. Indeed due to a build problem the Ubuntu 20.04 package of Veyon 4.4.2 is missing dependency information. I recommend using the PPA at https://launchpad.net/~veyon/+archive/ubuntu/stable/ and/or download and install the PPA Veyon package from https://launchpad.net/~veyon/+archive/ubuntu/stable/+build/19906599/+files/veyon_4.4.2-1~focal_amd64.deb

The issue has been fixed via 49227324f152c7105b35bd961a616af52d65ad09 and will be included in the next release.
