### ISSUE TITLE
Some screens are never displayed

### ISSUE THREAD

**Issue by cpdsfp** [veyon/veyon#673]
Hello!

From some weeks ago we have this problem:

In the Veyon Master some PCs status are  "Online and connected", and the screen is displayed as usual. 

But, when we try to access the PC, or only display the screen, he never connects, stay in an eternal attempting of connection, and in the Veyon Master the screen turns black, or sometimes red.

That problem mostly occurs with new PCs, but some old PCs who ever worked are now showing the same problem.

We tried fresh installation of the newest version of Veyon, even format the master PC, but nothing changes that.

What may be causing this problem?

Sorry our bad english and thanks for this awesome software.

**Comment by cpdsfp** [comment]
We installed the 4.1.7 version on the PC's with the problem and now they are working.

**Comment by tobydox** [comment]
Can you please try with the latest 4.5.1 release?

**Comment by cpdsfp** [comment]
Yes, tryed today and still not working, neither i can access the PC neither the PC can access other PC's with Veyon 4.4.2.

**Comment by tobydox** [comment]
Are you using the 32 or 64 bit version?

**Comment by cpdsfp** [comment]
The 64 bit version.

**Comment by tobydox** [comment]
Unfortunately we don't have a solution for this issue since we can't reproduce it. You could try to use Veyon with an external VNC server (e.g. UltraVNC or TightVNC installed in parallel) and configure the Veyon Service to use the external VNC server – just in case the issue is related to the builtin lightweight version of UltraVNC.
