### ISSUE TITLE
LDAP Auth for Master Login in Windows

### ISSUE THREAD

**Issue by LoPablo** [veyon/veyon#696]
We are currently in the process of deploying Veyon to all of our schools Computers. Everything is working fine so far, Machines are pulled from LDAP (Active Directory) and only certain AD-Groups are allowed to use Veyon / have access to other PCs.

However we have some Teachers with Computers or Notebooks that are not joined to the AD-Domain. Just like in issue #456 it is not sufficient to just replace the domain name in front of the username. Looking if there was a fix for this i took a trip through the code of Veyon and noticed that there is a LDAP-Authentication Provider including a login-window inside the ldap Plugin. 

Is this a provider for an auth method or is this a provider for something else? Is this a thing you are working on or should i myself lay hands on developing an auth provider for ldap? I the General settings under Auth Providers I can only select the key based and the logon auth which is not working for our scenario.

**Comment by tobydox** [comment]
You're right, there's code for LDAP authentication in the master branch. It will be shipped with Veyon 5 next year. Since it's based on the refactored modularized authentication support, it's not possible to backport it to Veyon 4. If desired, I can provide an unsupported Windows build of the current master branch which should basically work nearly as stable as Veyon 4.

**Comment by LoPablo** [comment]
Ok so the feature is on its way. Sounds good. If it doesn't make any trouble we would test out the unsupported Windows build, just to try it out with some PCs.
Meanwhile I shall take a look at compiling on Mac. We don't have any School PCs with MacOs on it, but some teachers which also want to use Veyon Master on it.

**Comment by tobydox** [comment]
Please find the most recent build for Windows attached. Since the authentication layer has been revised completely, you'll find a new configuration page "Authentication" where you can enable, configure and test the individual authentication methods. Please note that you'll have to install this version on both teacher and student computers since the network protocol has changed between Veyon 4 and 5.

[veyon-4.99.0.641-win64-setup.exe.zip](https://github.com/veyon/veyon/files/5641122/veyon-4.99.0.641-win64-setup.exe.zip)
