### ISSUE TITLE
Veyon on a Chromebook

### ISSUE THREAD

**Issue by awame** [veyon/veyon#708]
Hi,

I've installed Veyon on a Chromebook (on Linux beta). This Chromebook is the client. I can use veyon-configurator.
From the master (on Windows) I've added the Chromebook with his local address (192.168.0.117). I can see that the master is able to contact the Chromebook because when I close the Chromebook, the Chromebook icon goes gray on Veyon Master. But I cannot make the link between 192.168.0.117 and the Linux VM address (100.115.92.192). Is there a way to do that, or I can forget right now Veyon on a Chromebook ?

One more thing. When I start veyon-configurator on the Chromebook, I have : "CryptoCore::decryptPassword(): failed to decrypt password!". What can I do ?

**Comment by tobydox** [comment]
Are you running Linux natively on the Chromebook or are you running ChromeOS with Linux support layer. If the latter one, you won't be able to access the Chromebook since Linux apps are ran in a sandbox (like a virtual machine) and are not able e.g. to grab the display contents (which would be required by the internal VNC server).

**Comment by awame** [comment]
It's ChromeOS with Linux support layer. So, no need to insist. Thanks.

Any plan for Veyon and Chromebooks ?

**Comment by tobydox** [comment]
Due to technical limitations and lacking APIs in Chrome OS for any kind of remote control functionality, we're unable to port it to Chrome OS :-( All Veyon Master can detect is whether the host can be pinged. That's why the icon changes between red (host online but no Veyon Server running) and gray (host not reachable via ping).
