### ISSUE TITLE
Veyon Master crashes after clicking on a computer

### ISSUE THREAD

**Issue by Blakdawn** [veyon/veyon#729]
installs fine. All tests on config work.

opening veyon master works and it shows a list of computers, but selecting any causes it to close after a few seconds doing nothing.

looking on event viewer it reports that the fault is with qt5core.dll.

have tried the previous version (updated master only) with the same issue.

all comps running windows 10 20h2

**Comment by tobydox** [comment]
This is a bug in Veyon and happens if you did not enter a hostname/IP address for the corresponding computer (in Veyon Configurator -> Locations/hosts). Please make sure to specify a valid hostname/IP address for each computer. The program should not crash then. The crash will be fixed in the upcoming 4.5.6 release (but you won't be able to connect to computers which do not have a valid hostname/IP address).
