### ISSUE TITLE
Windowsupdate: Clients not reachable anymore

### ISSUE THREAD

**Issue by TUXBLN** [veyon/veyon#731]
[VeyonConfigurator.log](https://github.com/veyon/veyon/files/6388541/VeyonConfigurator.log)
[VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log](https://github.com/veyon/veyon/files/6388543/VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log)

After the most recent windows updates on the clients the master only shows clients as yellow (not running)
We cannot get it back to run. Just can’t figure out the issue, firewall is completely deactivated on the devices because it’s a complete internal network
![0C02F306-C0CC-4FD8-B595-2ED2B0C3F0AB](https://user-images.githubusercontent.com/72676748/116334471-8ec3c780-a7d5-11eb-8d88-91264d94c325.png)

After rolling back windows getting rid of THIS update (KB5001337) it works again ON SOME machines, not all. Please look into!
![6A044AFE-6A73-4EAA-856D-266E70828D0B](https://user-images.githubusercontent.com/72676748/116335148-a51e5300-a7d6-11eb-99ea-309234b0a7e0.png)

it’s KB5001337

**Comment by tobydox** [comment]
Thank you very much for your bug report! It looks like you're (still) running Windows 10 19H2 (10.0.18363). Running Veyon 4.5.5 on Windows 10 20H2 with the corresponding update (KB5001330, same as KB5001337 but for 20H2) is working fine here. Can you try to set the Veyon Service start do "delayed"? A user reported this improved reliability for him. However since this issue seems to be environment/installation specific, we can't deal with that issue here (for free) any further. For commercial support please contact sales@veyon.io.
