### ISSUE TITLE
Can't build veyon 4.7.3 in Windows

### ISSUE THREAD

**Issue by kevintanu** [veyon/veyon#819]
Hello,

I'm a Junior Software Developer
I have tried everything I can think of to build Veyon Open Source on Windows.

I have tried:

1. Tried the cross compilation process explained here:

https://github.com/jopsnow/veyon/wiki/Cross-compiling-for-Windows
but the ppa:tobydox/mingw-w64 is missing a lot of libraries.

2. Tried building using Msys2: Error 0xc0000142
![image](https://user-images.githubusercontent.com/41889426/174418745-e71a5a81-1924-46a3-97e8-d8326d1c22f9.png)

error building Veyon

3. Tried using docker Arch Linux Package: can't build openldap on mingw64

4. Try downgrading Veyon, same error 0xc0000142

I have been tasked to add some features on Veyon, such as gain access VNC from browser
I have knowledge using Unity3d (Primary), Elixir, NodeJs, and Flutter

May someone help me solve my problem
Thank you

**Comment by tobydox** [comment]
We no longer support building Veyon for Windows based on these instructions nor do we for msys2 since this has been abused by several companies in the past. Official Veyon builds for Windows are provided by Veyon Solutions only in order to guarantee malware-free genuine installers with signed binaries.
