### ISSUE TITLE
"Start application" How to empty list?

### ISSUE THREAD

**Issue by matedon** [veyon/veyon#878]
In Veyon Master: "Start application" or the old name of this function "Run program".
I have coosen: "Custom application" and checked: "Remember and add to application menu".
Ok. The command is remembered and I can choose that again, BUT not able to delete or edit.
I tought I will able to edit the commands in Veyon Configurator / Applications & websites. But no.
How can I erase all commands whitout the need of reinstall whole Veyon?
Thank you!

**Comment by matedon** [comment]
I am using Windows 10 on host and remote computers too and the newest Veyon 4.7.5.

**Comment by niltwill** [comment]
While the desired item (or command) is highlighted, press the "Delete" button. You need to do this one-by-one until it's empty.

Alternatively, you can remove or edit these entries in a file called "VeyonMaster.json".

In Windows by default, that means: `C:\Users\<username>\AppData\Roaming\Veyon\Config\VeyonMaster.json`
In Linux by default, it's located at: `~/.veyon/Config/VeyonMaster.json`
(or somewhere similar)

These are listed as a "JsonStoreArray" right at the beginning of the file ("DesktopServices"), under "PredefinedApplications" (you can also find the "PredefinedWebsites" here).

It may be the best to manage these in **Veyon Configurator** itself (at "Applications & websites"), instead of adding them in Veyon Master. So that you can remove and edit them as needed there. In the case of these entries, the delete button on highlighting isn't going to work.
