### ISSUE TITLE
Veyon-Configurator.exe -L & -A do not seem to be implimented

### ISSUE THREAD

**Issue by PatCahill77** [veyon/veyon#89]
Windows 7 x64
Veyon RC3 (3.99.7)

The commands
veyon-configurator.exe -ListConfig
veyon-configurator.exe -L
veyon-configurator.exe -Silent -ApplySettings Base_Config.json
veyon-configurator.exe -Silent -A Base_Config.json
both open the Configurator window.

However 
veyon-configurator.exe -Silent -ImportPublicKey {somwhere}\veyon_public_key.key.txt
does seem to work (or at least it doesnt open Configurator)

**Comment by tobydox** [comment]
Hi,

all of the command line operations except key management have been moved into the separate Veyon Control tool (veyon-ctl). Please use "veyon-ctl config help" or "veyon-ctl help" for more information :-)

You can also pass the configuration file to the installer, see http://docs.veyon.io/en/latest/admin/silent-installation-on-windows.html for details

Toby

**Comment by MSTigers** [comment]
/S /ApplyConfig=%cd%veyonconfig2.json  Doesn't work for me. The program installs but errors for the config. I also tried /S /ApplyConfig=S:\veyonconfig2.json  where S:\ is the absolute path, both with and without "" around the directory.

Used the directions you linked in the last comment.

Error reads:  "Could not apply specified configuration file!" 

EDIT: Before submitting I wanted to try to manually load the config again just to be safe. S:\ is a network drive located on all computers. When trying to manually load it, looks like the Veyon Configurator cannot see mapped network drives which explains why the absolute location isn't working either.

Not end of the world, I'll have to run a separate task to transfer the json over locally, then run the installer, point to absolute path, then remove the file afterwards. Leaving this comment here since it seems relevant and may help someone else out.
