### ISSUE TITLE
Veyon 4.7.5 Bug Fix and LTS

### ISSUE THREAD

**Issue by MIAIONE** [veyon/veyon#923]
Hello! I've encountered a very tricky issue. As stated on the download page, the EOL version of Windows requires the use of 4.7.5. However, this version seems to exhibit noticeable video stuttering when playing videos, unlike 4.8.x. Unfortunately, I cannot install 4.8.x because Qt6.x no longer supports Windows 7.

I attempted to download version 4.7.5 separately to find the bug, but I couldn't locate it. Therefore, I decided to use 4.8.x and change the Qt target version to 5.x, even though it is quite challenging. I compiled using both WSL (Ubuntu 22) and Windows MSVC, encountering issues such as qca-qt5 and OpenSSL not being found (although I have resolved them). However, when I try to proceed to the next step, I cannot find any functions and header files required in LibVNCServerIntegration.cmake.

So, I hope the developers can provide a fix for version 4.7.5, as I have not been able to build it successfully. Additionally, this bug significantly impacts the user experience. As the last version supporting Windows 7, I hope an LTS (Long-Term Support) can be provided.

**Comment by tobydox** [comment]
Thank you for your submission. I'm really sorry but we do not support EOL versions of any operation system in general. Additionally we do not publicly support custom Windows builds of Veyon due to abuses in the past. We offer custom builds or build toolchains to paying customers. If you're interested, contact us via sales@veyon.io to discuss the details.
