### ISSUE TITLE
Veyon master is displaying the parent containers

### ISSUE THREAD

**Issue by adminds49** [veyon/veyon#955]
Hello,
when i  user "Computer containers or OU" to identify computer location, veyon master displays the parent UO instead of the right UO of he computer. Not on every UO, maybe 50/50... I don't see any difference between an UO where it works fine and others.

![2024-05-24 11_13_50-Window](https://github.com/veyon/veyon/assets/170716700/193ee76b-65df-4ca3-8d71-cf44206c2af3)
![2024-05-24 11_13_11-Window](https://github.com/veyon/veyon/assets/170716700/3d3d61dd-ad81-4d10-9b21-fe57cf8eae3f)

**Comment by adminds49** [comment]
![2024-05-24 11_27_50-Window](https://github.com/veyon/veyon/assets/170716700/90532185-fab6-4550-9931-ebe86582d77f)

**Comment by tobydox** [comment]
Do you have recursive search enabled? Can you post a screenshot of your LDAP/AD settings?

**Comment by adminds49** [comment]
Hello Tobias,

Yes it is enabled. Here is my config:
![image](https://github.com/veyon/veyon/assets/170716700/c2c43644-d76a-4514-9da2-c33fea13138e)
![image](https://github.com/veyon/veyon/assets/170716700/249a8b72-2571-4738-8024-7307bd057c77)
![image](https://github.com/veyon/veyon/assets/170716700/736dd950-036a-4516-bfb8-397c14709256)

Regards

**Comment by tobydox** [comment]
Thank you for the screenshots! The configuration look fine to me. Which locations does Veyon resolve in general? Only the top level OUs or all OUs? It should show all OUs while in top-level OUs you should see all computers of all sub-OUs. At least this is the expected behaviour based on the code ;-)

Please also note that the LDAP/AD Basic plugin does not really support nested hierarchies/OUs. For this you'd need the commercial LDAP Pro Add-on. You could give it a try to see if it handles your OUs better. Simply install the add-ons and configure the LDAP Pro add-on (and switch the network object directory on the first page). The add-on can be tested for a few minutes each time without a license so it would be interesting to see if it works for your environment.

**Comment by adminds49** [comment]
It is quite random, some rooms are displayed correctly, others are displaying top level:
![image](https://github.com/veyon/veyon/assets/170716700/c2d30eb3-0fb3-4a81-8570-3e219486078e)
I'll try to test the pro add-on (I purchased it in 01/2022, but finally never used it)

**Comment by adminds49** [comment]
Thanks ! it seems to work very well with LDAP Pro. Does the license I have for LDAP-PRO add-on include others add-ons like InternetAccessControl ? I tried it on 1 computer, but it says i use the demo version.

**Comment by tobydox** [comment]
Thank you for the feedback! I'm happy to hear the add-on works for you. Unless you have a bundle license, the LDAP Pro License only works for the LDAP Pro add-on. You can contact us via e-mail sales@veyon.io to if you have further questions regarding the add-ons licensing. Then I can also check what add-ons you have licensed.
