### ISSUE TITLE
Using Veyon's features programmatically

### ISSUE THREAD

**Issue by Petrozilia** [veyon/veyon#963]
I think it would be great to have a way to use Veyon's features programmatically, specifically the **screen lock** and **user login** features.
This will allow IT admins more flexibility and control, and enable the integration of Veyon with custom/internal tools and automation workflows.

Perhaps this could be done using the REST API?

As far as I could tell, currently both the Veyon CLI and the RESP API can only enable/disable those features altogether.

**Comment by tobydox** [comment]
Yes we do have the WebAPI plugin which offers a REST API, see https://docs.veyon.io/en/latest/developer/webapi.html for details. You can easily start/stop certain features such as screen lock as well as user login, see https://docs.veyon.io/en/latest/developer/webapi.html#feature-control for details.

Due to a bug in the build process of 4.8.3, the add-on is not available in the Windows version of 4.8.3 but will be available again in 4.8.4 soon.
